# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Create the orb for the code coverage upload
orbs:
  codecov: codecov/codecov@3.2.4

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  allelefinder:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: ubuntu:22.04
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Setup Environment and Run Tests
          command: |
            apt update
            apt install -y wget coreutils curl gnupg
            wget -O Mambaforge.sh  "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
            bash Mambaforge.sh -b -p "${HOME}/conda"
            source "${HOME}/conda/etc/profile.d/conda.sh"
            source "${HOME}/conda/etc/profile.d/mamba.sh"
            conda config --add channels olcbioinformatics
            conda config --add channels bioconda
            conda config --set always_yes yes --set changeps1 no
            conda activate
            mamba create -n allelefinder python=3.9.12
            source activate allelefinder
            mamba install \
              "coloredlogs=15.0.1=pyhd8ed1ab_3" \
              "geneseekr=0.5.0=py_12" \
              "pytest=7.2.1=pyhd8ed1ab_0" \
              "pytest-cov=4.0.0=pyhd8ed1ab_0"
            pip install -e .
            python -m pytest tests/ --cov=allele_tools/ --cov-config=.coveragec --cov-report=xml:test_reports/allele_finder.xml -s
      - store_artifacts:
          path: test_reports/
          destination: circleci-docs
      - codecov/upload:
          file: /root/project/test_reports/allele_finder.xml
          xtra_args: -R /root/project/
workflows:
    build_and_test:
        jobs:
          - allelefinder:
              filters:
                branches:
                  ignore: gh-pages