# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Create the orb for the code coverage upload
orbs:
  codecov: codecov/codecov@4.1.0

# Define a job to be invoked later in a workflow.
jobs:
  allelefinder:
    # Specify the execution environment. Using miniconda3 image from Dockerhub.
    docker:
      - image: continuumio/miniconda3
    environment:
      PYTHON_VERSION: 3.9.12
    # Add steps to the job
    steps:
      # Checkout the code from the repository
      - checkout
      - run:
          name: Setup Environment and Run Tests
          command: |
            # Install curl
            # Install curl and gnupg
            apt-get update && apt-get install -y curl gnupg
            # Add necessary channels for conda
            conda config --add channels olcbioinformatics
            conda config --add channels bioconda
            # Set conda configuration options
            conda config --set always_yes yes --set changeps1 no
            # Install mamba
            conda install mamba -c conda-forge
            # Create a new conda environment with a specific version of Python
            mamba create -n allelefinder python=${PYTHON_VERSION}
            # Activate the environment
            source activate allelefinder
            # Install BLAST using mamba
            mamba install -c bioconda blast
            # Install the current project (in editable mode) using pip
            pip install -e .
            # Run pytest with coverage options
            pytest tests/ --cov=allele_tools/ --cov-config=.coveragerc --cov-report=xml:test_reports/allele_finder.xml -s
      - run:
          name: Check Test Reports
          command: |
            if [ ! -f /root/project/test_reports/allele_finder.xml ]; then
              echo "Test reports not found!"
              exit 1
            fi
      # Store the test reports as artifacts
      - store_artifacts:
          path: test_reports/
          destination: circleci-docs
      # Upload the coverage report to codecov
      - codecov/upload:
          files: /root/project/test_reports/allele_finder.xml

# Define a workflow that runs the defined job
workflows:
  build_and_test:
    jobs:
      - allelefinder:
          filters:
            branches:
              # Ignore the gh-pages branch
              ignore: gh-pages