# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Create the orb for the code coverage upload
orbs:
  codecov: codecov/codecov@3.2.4

# Define a job to be invoked later in a workflow.
jobs:
  allelefinder:
    # Specify the execution environment. Using Ubuntu 22.04 image from Dockerhub.
    docker:
      - image: ubuntu:22.04
    # Add steps to the job
    steps:
      # Checkout the code from the repository
      - checkout
      - run:
          name: Setup Environment
          command: |
            # Update the package lists for upgrades for packages that need upgrading, as well as new packages that have just come to the repositories
            apt update
            # Install necessary packages
            apt install -y wget coreutils curl gnupg
            # Download Mambaforge installer
            wget -O Mambaforge.sh  "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
            # Install Mambaforge
            bash Mambaforge.sh -b -p "${HOME}/conda"
            # Source the conda and mamba shell scripts to set up the environment
            source "${HOME}/conda/etc/profile.d/conda.sh"
            source "${HOME}/conda/etc/profile.d/mamba.sh"
            # Add necessary channels for conda
            conda config --add channels olcbioinformatics
            conda config --add channels bioconda
            # Set conda configuration options
            conda config --set always_yes yes --set changeps1 no
            # Activate the base conda environment
            conda activate
            # Create a new conda environment with a specific version of Python
            mamba create -n allelefinder python=3.9.12
            # Activate the newly created conda environment
            source activate allelefinder
      - run:
          name: Install Dependencies
          command: |
            # Install necessary Python packages using mamba
            mamba install \
              "coloredlogs=15.0.1=pyhd81ab_3" \
              "geneseekr=0.5.0=py_12" \
              "pytest=7.2.1=pyhd8ed1ab_0" \
              "pytest-cov=4.0.0=pyhd8ed1ab_0"
            # Install the current project (in editable mode) using pip
            pip install -e .
      - run:
          name: Run Tests
          command: |
            # Run pytest with coverage options
            python -m pytest tests/ --cov=allele_tools/ --cov-config=.coveragec --cov-report=xml:test_reports/allele_finder.xml -s
      # Store the test reports as artifacts
      - store_artifacts:
          path: test_reports/
          destination: circleci-docs
      # Upload the coverage report to codecov
      - codecov/upload:
          file: /root/project/test_reports/allele_finder.xml
          xtra_args: -R /root/project/

# Define a workflow that runs the defined job
workflows:
  build_and_test:
    jobs:
      - allelefinder:
          filters:
            branches:
              # Ignore the gh-pages branch
              ignore: gh-pages