name: Build and Release Conda Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: allelefinder_env
        python-version: 3.9.12
        auto-activate-base: false
    - name: Download hash artifact
      uses: actions/download-artifact@v2
      with:
        name: hash
    - name: Read hash
      id: read_hash
      run: |
        echo "HASH=$(cat hash.txt)" >> $GITHUB_ENV
    - name: Update meta.yaml
      run: |
        sed -i "s/{{ version }}/$(echo ${GITHUB_REF#refs/tags/})/g" recipes/meta.yaml
        sed -i "s|{{ url }}|https://pypi.io/packages/source/a/allelefinder/allelefinder-$(echo ${GITHUB_REF#refs/tags/}).tar.gz|g" recipes/meta.yaml
        sed -i "s/{{ sha256 }}/${{ env.HASH }}/g" recipes/meta.yaml
    - name: Build Conda package
      run: |
        conda build .
    - name: Upload Conda package
      uses: actions/upload-artifact@v2
      with:
        name: my_package
        path: $CONDA_BLD_PATH/noarch/my_package-*.tar.bz2