name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Get file names
      id: get_filenames
      run: |
        echo "tar_file=$(ls dist/*.tar.gz)" >> $GITHUB_ENV
        echo "whl_file=$(ls dist/*.whl)" >> $GITHUB_ENV
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset (.tar.gz)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ${{ env.tar_file }}
        asset_name: ${{ env.tar_file }}
        asset_content_type: application/gzip
    - name: Upload Release Asset (.whl)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ${{ env.whl_file }}
        asset_name: ${{ env.whl_file }}
        asset_content_type: application/zip
    - name: Setup Conda
      run: |
        echo "deb [arch=amd64] http://repo.anaconda.com/pkgs/misc/deb stable main" | sudo tee /etc/apt/sources.list.d/conda.list
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 34161F5BF5EB1D4BFBBB8F0A8AEB4F7F63F9B278
        sudo apt-get update
        sudo apt-get install conda
    - name: Install Conda dependencies
      run: |
        conda install conda-build anaconda-client
    - name: Update meta.yaml
      run: |
        sed -i "s/{{ version }}/$(echo ${GITHUB_REF#refs/tags/})/g" recipe/meta.yaml
        sed -i "s|{{ url }}|https://github.com/${{ github.repository }}/archive/${{ github.ref }}.tar.gz|g" recipe/meta.yaml
    - name: Build Conda package
      run: |
        conda build recipe
    - name: Convert Conda package
      run: |
        conda convert --platform all $CONDA_PREFIX/conda-bld/linux-64/*.tar.bz2 --output-dir recipe/conda-bld/
    - name: Upload Conda package
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload conda-bld/**/*.tar.bz2