name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Get file names
      id: get_filenames
      run: |
        echo "tar_file=$(ls dist/*.tar.gz)" >> $GITHUB_ENV
        echo "whl_file=$(ls dist/*.whl)" >> $GITHUB_ENV
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Publish to GitHub Packages
      run: |
        python -m twine upload --repository-url https://upload.pypi.org/legacy/ --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} dist/*
    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset (.tar.gz)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ${{ env.tar_file }}
        asset_name: ${{ env.tar_file }}
        asset_content_type: application/gzip
    - name: Upload Release Asset (.whl)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ${{ env.whl_file }}
        asset_name: ${{ env.whl_file }}
        asset_content_type: application/zip